
package com.app;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimpleCalculatorImplService", targetNamespace = "http://app.com/", wsdlLocation = "http://127.0.0.1:8082/calculator?wsdl")
public class SimpleCalculatorImplService
    extends Service
{

    private final static URL SIMPLECALCULATORIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMPLECALCULATORIMPLSERVICE_EXCEPTION;
    private final static QName SIMPLECALCULATORIMPLSERVICE_QNAME = new QName("http://app.com/", "SimpleCalculatorImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8082/calculator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMPLECALCULATORIMPLSERVICE_WSDL_LOCATION = url;
        SIMPLECALCULATORIMPLSERVICE_EXCEPTION = e;
    }

    public SimpleCalculatorImplService() {
        super(__getWsdlLocation(), SIMPLECALCULATORIMPLSERVICE_QNAME);
    }

    public SimpleCalculatorImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMPLECALCULATORIMPLSERVICE_QNAME, features);
    }

    public SimpleCalculatorImplService(URL wsdlLocation) {
        super(wsdlLocation, SIMPLECALCULATORIMPLSERVICE_QNAME);
    }

    public SimpleCalculatorImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMPLECALCULATORIMPLSERVICE_QNAME, features);
    }

    public SimpleCalculatorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleCalculatorImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SimpleCalculatorImpl
     */
    @WebEndpoint(name = "SimpleCalculatorImplPort")
    public SimpleCalculatorImpl getSimpleCalculatorImplPort() {
        return super.getPort(new QName("http://app.com/", "SimpleCalculatorImplPort"), SimpleCalculatorImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleCalculatorImpl
     */
    @WebEndpoint(name = "SimpleCalculatorImplPort")
    public SimpleCalculatorImpl getSimpleCalculatorImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://app.com/", "SimpleCalculatorImplPort"), SimpleCalculatorImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMPLECALCULATORIMPLSERVICE_EXCEPTION!= null) {
            throw SIMPLECALCULATORIMPLSERVICE_EXCEPTION;
        }
        return SIMPLECALCULATORIMPLSERVICE_WSDL_LOCATION;
    }

}
